### ISSUE TITLE
use-prosemirror is not a good fit for a React Stateless Functional Component ?

### ISSUE THREAD

**Issue by Bartaf83** [dminkovsky/use-prosemirror#10]
I'm using the use-prosemirror's ProseMirror component inside a React Stateless Functional Component (BookEditor).

```
const BookEditor = React.memo((props, nextProps) => {

  const contentDiv = document.createElement('div');
  contentDiv.innerHTML = props.textPage.content; // getting content from props's textPage
  
  const isFirstRun = useRef(true);
  useEffect(
    () => {
      if (isFirstRun.current) {
        isFirstRun.current = false;
        return;
      } else {
        const { view } = useProseMirrorComp;
        const { state } = view;
        const { schema, plugins } = state;
        const doc = DOMParser.fromSchema(mySchema).parse(contentDiv);
        let newState = EditorState.create({ schema: schema, doc, plugins: plugins });
        view.updateState(newState);
      }
    },
    [props.textPage],
  );
  
// defining my custom nodes here
  const editorTitleHeader = {...};
  const editorTitle = {...};
  
  schema.spec.nodes = schema.spec.nodes.append({
    editorTitle,
    editorTitleHeader,
  });
  nodes.doc.content = 'editorTitle block+';
  const mySchema = new Schema({
    nodes: addListNodes(schema.spec.nodes, 'paragraph block*', 'block'),
    marks: schema.spec.marks,
  });

  const rules = [...];

  const doc = DOMParser.fromSchema(mySchema).parse(contentDiv);
  const [state, setState] = useProseMirror({
    doc,
    schema: mySchema,
    plugins: [
      inputRules({ rules: rules }),
      columnResizing(),
      tableEditing(),
      keymap({
        Tab: goToNextCell(1),
        'Shift-Tab': goToNextCell(-1),
      }),
    ].concat(exampleSetup({ schema, menuContent: menu })),
    destroy: () => {
      console.log('BookEditor :  destroy!!!!!!!!! ');
    },
  });
  return (
    <div id="use-prosemirror-comp">
      <ProseMirror
        state={state}
        dispatchTransaction={transaction => {...}}
        ref={r => {
          useProseMirrorComp = r;
        }}
        nodeViews={...}
      >
        <div id="content" />
      </ProseMirror>
    </div>
  );
});
```
I used use-prosemirror as it's supposed to make prosemirror fit better with react.
But in such as case of using it in inside a React Stateless Functional Component, it seems not fitting well.
I'm still relatively new with react hooks..

When the Stateless Functional Component is called again for a new rendering, all the < ProseMirror > will be reinstantiated as it lies in the body of the function. 

And each time that happens, a new content will be passed to it (through contentDiv which will be parsed and the state doc generated) but i noticed that the < ProseMirror > fails to update the content even when that happen (if there is no state update view.updateState(newState); inside the  useEffect's isFirstRun.current == false case).

And i also think that it's not the best performance fit to reinstanciate the whole < ProseMirror > in each Stateless Functional Component re-rendering.

The Stateless Functional Component should return a content thought, that's why i can't only return the <ProseMirror> in the useEffect's isFirstRun.current == true case (which is the old componentDidMount hook equivalent). So i still have to return it in each rendering and then update its content in the useEffect's isFirstRun.current == false case (equivalent to the old componentDidUpdate).

I got a recommandation to use the use-prosemirror for react but i don't think it's a good idea.
Any thoughts about this ?
Last question : does React.memo have an effect in all this and the performance ?

**Comment by dminkovsky** [comment]
Hello @Bartaf83!

Thank you for opening this issue! I am sorry, but it is very long and I am not sure what the issue is. Can you please provide a shorter example that will make it clearer for me?

Sincerely,
Dmitry
