### ISSUE TITLE
Passing classes to <ProseMirror>

### ISSUE THREAD

**Issue by michael** [dminkovsky/use-prosemirror#12]
Hi @dminkovsky!

I just wanted to make use of passing className='article' to `<ProseMirror ..>`. The result is this structure:

![image](https://user-images.githubusercontent.com/2931/114430121-66757f80-9bbe-11eb-93f1-0e166a3ca258.png)

Would it be possible to have the classes assigned along .ProseMirror instead of a wrapping div around?

I'd like to get `class="ProseMirror article"` so I can use the same CSS for display and editing.

Thank you :)

**Comment by dminkovsky** [comment]
Hi @michael!

Thanks for opening this issue. Looks like the `attributes` editor prop allows you to do this: 

* https://prosemirror.net/docs/ref/#view.EditorProps.attributes. 
* https://github.com/ProseMirror/prosemirror-view/blob/e878a099871b9f44329674aed25ba6e40b51b222/src/index.js#L384-L392

I'll add a little note to the README about this, too.

**Comment by dminkovsky** [comment]
Just tested it out in the sandbox example and yes, just add the `attributes` prop with an object (or function returning an object) like `{class: "myProseMirror anotherClass"}` and the resulting class on the editor will be `ProseMirror myProseMirror anotherClass`

**Comment by michael** [comment]
Super that does the trick. 👍 Thanks a lot!
