### ISSUE TITLE
Support for using EditorView subclasses

### ISSUE THREAD

**Issue by abingham** [dminkovsky/use-prosemirror#18]
Is there any way to use a subclass of `EditorView` instead of `EditorView` itself with `use-prosemirror`? Looking through the code, it looks like `EditorView` is hardcoded, but perhaps I've missed something.

If it's not supported, would you consider supporting it? I'm not sure the best way to do it, but perhaps the class could be passed in as a property. I'd be happy to help with a PR, but I like to first make sure I do it in the way you prefer (I'm not a terribly experienced JS programmer, so I may "obvious" approaches).

**Comment by dminkovsky** [comment]
Hi @abingham. Thanks for opening this issue. 

Yep, `EditorView` is hardcoded. It's the class that is concretely instantiated: https://github.com/dminkovsky/use-prosemirror/blob/82d93e376e595f5784c7a584f91b759a2d43f62b/src/ProseMirror.tsx#L62-L65

I'm not a ProseMirror expert, but I'm not aware of any reason not to extend `EditorView`, which is not something I'd considered but seems reasonable. To support that I would:

1. Add a type parameter `V` to `function ProseMirror` that's like `function ProseMirror<V extends EditorView = EditorView>`.
2. Add the same type parameter to `EditorProps` such that `EditorProps<V extends EditorView = EditorView>`
3. Add a prop to `EditorProps<V>` that is a factory that returns E.
4. Use that factory if it was passed in the props to build the editor view instance.

I don't have time to do this right now but if you want to do a PR I would be happy to review.

Thanks again!

**Comment by abingham** [comment]
Sure, I'll try to put something together this morning. Thanks!

**Comment by abingham** [comment]
> Add the same type parameter to EditorProps such that EditorProps<V extends EditorView = EditorView>

Do you mean `PropsBase` rather than `EditorProps`?

**Comment by dminkovsky** [comment]
I started typing it out but then I realized it was easier to just edit the file :) Please see #19.

**Comment by dminkovsky** [comment]
Actually, unfortunately there's a TS issue there I'm not seeing how to fix :/

**Comment by dminkovsky** [comment]
... because I was making way too complicated :). Just pushed what I think should work for you?

**Comment by abingham** [comment]
That PR seems to work well for me.

**Comment by dminkovsky** [comment]
Looks like it's published.
