### ISSUE TITLE
Problem when using ProseMirror's node views

### ISSUE THREAD

**Issue by michael** [dminkovsky/use-prosemirror#5]
I got a really strange behavior when i'm activating node views. I can't place the cursor anymore, so editing breaks. Could you check if you observe the same? 

I'm suspecting this line in ProseMirror.tsx:

```js
viewRef.current?.setProps(buildProps(restProps));
```

Maybe the nodeViews prop can only be set initially not on each rerender. But that's just a guess.

Here's my additions that lead to the problem.

```js
class ImageView {
  constructor (node) {
    // The editor will use this as the node's DOM representation
    this.dom = document.createElement('img')
    this.dom.src = 'https://letsken.imgix.net/'+node.src
    this.dom.addEventListener('click', e => {
      console.log('You clicked me!')
      e.preventDefault()
    })
  }

  stopEvent () { return true }
}
```

```js
const nodeViews = {
  image (node) { return new ImageView(node) }
}

...
<ProseMirror ref={viewRef} state={state} onChange={handleChange} nodeViews={nodeViews} />
```

**Comment by dminkovsky** [comment]
Hi @michael, 

It's probably this issue: https://github.com/dminkovsky/use-prosemirror/issues/1. The simplest solution I found (there may be another one listed on that issue) is to just have the nodeView param be identity-stable. Meaning, you don't re-create it all the time. To have a JS object's identity be stable, if you are using:

- a class component, store it on the instance (`this`)
- a function component, [store it on a ref with `useRef()`](https://github.com/Andarist/use-constant/blob/master/src/index.ts).

I am thinking of expanding this implementation to make this simpler. The API I have been thinking of would allow you to just pass in React components for your nodeViews. This change would make the library more opinionated, but easier to use.

**Comment by dminkovsky** [comment]
Here's how it is in mine:

```
function MyProseMirror(props) {
    const isMounted = useIsMounted();
    const [nodeViewSpecs, setNodeViewSpecs] = useState([]);
    const nodeViews = useConstant(() =>
        nodeView(isMounted, setNodeViewSpecs),
    );
    return (
        <>
            <ProseMirror state={state} onChange={onChange} nodeViews={nodeViews} />
            {nodeViewSpecs.map(({el, key, type, attrs}) => {
                let render;
                if (type === 'link_preview') {
                    const link = props.message!.links.find(
                        link => link.id === attrs.id,
                    );
                    // Link may not be found if link was just added
                    // and data in Apollo client has not yet caught up
                    render = link ? (
                        <LinkPreview link={link} />
                    ) : null;
                } else if (type === 'image') {
                    render = (
                        <ImageNodeView
                            id={attrs.id}
                            urls={props.urls}
                        />
                    );
                } else {
                    const attachment = props.message!.attachments.find(
                        a => a.id === attrs.id,
                    );
                    // Attachment may not be found if link was just added
                    // and data in Apollo client has not yet caught up
                    render = attachment ? (
                        <AudioTrack
                            attachment={attachment}
                            urls={props.urls}
                        />
                    ) : null;
                }
                return createPortal(render, el, key);
            })}
        </>
    );
}

function nodeView(
    isMounted: MutableRefObject<boolean>,
    setSpecs: Dispatch<React.SetStateAction<NodeViewSpec[]>>,
): {[name: string]: NodeViewFn} {
    return {
        image: buildNodeView,
        audio: buildNodeView,
        link_preview: buildNodeView,
    };
    function buildNodeView({attrs, type}: Node): NodeView {
        const el = document.createElement('div');
        el.setAttribute('class', `node-view ${type.name}`);
        const key = attrs.id || attrs.key;
        const spec: NodeViewSpec = {
            key: `${key}`,
            type: type.name,
            el,
            attrs,
        };
        // Hack around https://github.com/facebook/react/issues/18178#issuecomment-595846312
        setTimeout(() => {
            setSpecs(specs => [...specs, spec]);
        }, 0);
        return {
            dom: el,
            destroy,
        };
        function destroy() {
            // Avoid memory leak warnings after unmount
            if (isMounted.current) {
                // Hack around https://github.com/facebook/react/issues/18178#issuecomment-595846312
                setTimeout(() => {
                    setSpecs(specs => {
                        const next = [...specs];
                        next.splice(
                            specs.findIndex(({el}) => el === spec.el),
                            1,
                        );
                        return next;
                    });
                }, 0);
            }
        }
    }
}


```

**Comment by dminkovsky** [comment]
Let me know what you think about including it in the implementation and if you think it makes sense and have time for a PR, that would be awesome.

**Comment by dminkovsky** [comment]
@evangoer noticed you <3'ed #1. Maybe this is interesting to you, too.

**Comment by evangoer** [comment]
It is of interest. I addressed the basic problem by making my `nodeViews` identity-stable, as you suggested in the other issue.

The portal approach looks promising. My instinct is that most users of `use-prosemirror`, being React developers, would prefer the more opinionated method, but that's just a guess.

As a side note, great job creating `use-prosemirror`. I've experimented with several different RTEs and several different React integrations, and ProseMirror with use-prosemirror has been the clear winner. Thank you!

**Comment by michael** [comment]
Aw, I should have seen that issue. But thank you. I just solved it by defining the nodeViews constant outside of the React function. :) 

@dminkovsky I'd be all in for being able to define node views as React components too. I mean as long as there's no unwanted side-effects to expect. As I understand PM uses synchronous rendering while React uses async. Not that we run into some timing-issues with rendering which affects the editing. Then better bare metal. :)

For now maybe just state in the README that the nodeViews editorProp must be identity stable across renders.

**Comment by dminkovsky** [comment]
@evangoer

> The portal approach looks promising. My instinct is that most users of use-prosemirror, being React developers, would prefer the more opinionated method, but that's just a guess.

I think so, too. Bringing the node view instances into the render tree with state and then rendering them out with portals is a bit complicated, but I couldn't think of a cleaner way. I wasn't sure how else to do it, in order to render the node views with React. It's worked well as far as I've tested it.

> As a side note, great job creating use-prosemirror. I've experimented with several different RTEs and several different React integrations, and ProseMirror with use-prosemirror has been the clear winner. Thank you!

Hey thank you that's great to hear. I tried many RTEs, too, and ProseMirror was the only one that worked across all platforms. The BDFL model seems to be working in that project, too. Integrating it with React was a bit of work but that's why I published this. Please submit issues if you encounter any!

**Comment by dminkovsky** [comment]
> I'd be all in for being able to define node views as React components too. I mean as long as there's no unwanted side-effects to expect. As I understand PM uses synchronous rendering while React uses async. Not that we run into some timing-issues with rendering which affects the editing.

The approach above seems to be working for me, but yeah, I will need to test it more. I am particularly wondering how this holds up on slow, cheap Android devices, for example. I played around in a simulator, but I would really want to get some cheap devices as soon as possible. Seems to work well on desktops and iOS. So you're rendering your node views not with React? Sadly, I tried rendering them them "by hand" and found I didn't have the mental bandwidth for that :).

> For now maybe just state in the README that the nodeViews editorProp must be identity stable across renders.

That's a good idea. Will do that.

**Comment by michael** [comment]
There's so little do there in my project atm. Basically I just need to enhance img and video elements to compute the proper src properties. As soon as I need some more controls in the editor, then React for node views would be make a better choice for sure.

Thanks a lot for the help!

**Comment by dminkovsky** [comment]
@michael Makes sense! I avoided React rendering node views as long as I could, but React has taken over my brain and my audio node view was just too complicated, with state and everything, for me to switch paradigms. You're welcome! Please post any other issues you may have.
